/* ── the candidate → Uber-account lookup, rewritten for the index and pinned ─
   THE DEFECT, MEASURED ON PRODUCTION 2026-09-16. statusJoin() resolves a
   candidate's person key to the Uber account ids that person holds, once per
   candidate per segment, inside a lateral that already runs once per segment.
   Its own comment says it was made "SARGABLE, so this rides trip_person_key_idx
   instead of scanning". EXPLAIN (ANALYZE, BUFFERS) of the rows query over a
   16-day window said otherwise:

     -> Index Only Scan using trip_econ_day_idx on trip t3
        (actual time=692.331..1770.390 rows=1842 loops=28)

   1.77 s per execution, 28 executions, 49.6 s of a 55.1 s response — 90% of
   the query. Two arms joined by OR are one clause over two different columns,
   and the planner declined a BitmapOr because the second arm's
   coalesce(btrim(person_key),'') = '' is an expression no index covers. So it
   scanned an unrelated index end to end instead, which is the same work under
   a better name. The arms are now UNIONed, one indexable scan each.

   WHAT THIS FILE PROVES, AND WHY IT IS AN EQUIVALENCE TEST. A rewrite for a
   plan is only safe if it returns the same rows, and "the suite still passes"
   is not that proof — the route-level fixtures exercise one shape of this
   lookup. So both forms are run side by side, the OLD one written out here in
   full, over a fixture carrying every shape the column can be in, and asserted
   to agree key by key. Change either arm and the two disagree. */
import { PGlite } from '@electric-sql/pglite';
import { applySchema } from './schema.mjs';

let pass = 0, fail = 0;
const check = (n, ok, x = '') => { ok ? (pass++, console.log(`  ✓ ${n}`)) : (fail++, console.log(`  ✗ ${n} ${x}`)); };

const db = new PGlite();
await applySchema(db);

/* person_key is GENERATED from driver_name (sql/schema_v20.sql, regenerated by
   sql/schema_v53.sql), so the shapes are controlled through the name: a name
   gives a key, no name gives a NULL key and the account id has to stand in. */
const trip = async (id, platform, extId, name) => db.query(
  `INSERT INTO trip (external_id, platform, fleet_id, driver_ext_id, driver_name,
                     requested_at, plate)
   VALUES ($1, $2, 'ecosine', $3, $4, '2026-09-01T10:00:00Z', 'P1')`,
  [id, platform, extId, name]);

// One person, two accounts on two channels — the case the fold exists for.
await trip('t1', 'uber', 'u-amina', 'Amina Rashid');
await trip('t2', 'bolt', 'b-amina', 'Amina Rashid');
// A second person, so a key that matches must not drag the whole table back.
await trip('t3', 'uber', 'u-bilal', 'Bilal Haq');
// Named by the provider with no usable key: person_key is NULL, the id stands in.
await trip('t4', 'uber', 'u-ghost', null);
// The same nameless account again, so UNION's dedupe is actually exercised.
await trip('t5', 'uber', 'u-ghost', null);
// A row with no account id at all: excluded by both forms, on both arms.
await trip('t6', 'hotel', '', 'Amina Rashid');
await trip('t7', 'uber', null, null);

const OLD = `SELECT DISTINCT t3.driver_ext_id FROM trip t3
              WHERE (t3.person_key = $1
                     OR (coalesce(btrim(t3.person_key), '') = '' AND t3.driver_ext_id = $1))
                AND coalesce(btrim(t3.driver_ext_id), '') <> ''`;
const NEW = `SELECT t3.driver_ext_id FROM trip t3
              WHERE t3.person_key = $1
                AND t3.person_key IS NOT NULL AND t3.person_key <> ''
                AND coalesce(btrim(t3.driver_ext_id), '') <> ''
             UNION
             SELECT t3.driver_ext_id FROM trip t3
              WHERE t3.driver_ext_id = $1
                AND coalesce(btrim(t3.person_key), '') = ''
                AND coalesce(btrim(t3.driver_ext_id), '') <> ''`;

const setOf = async (sql, key) => (await db.query(sql, [key])).rows
  .map((r) => r.driver_ext_id).sort().join(',');

console.log('\nthe rewrite returns what the OR returned, on every shape of the column');

/* The keys a candidate can actually carry: a folded name, an account id
   standing in for a missing one, a name that is nobody's, and the two values
   that must never behave like a wildcard. */
const [{ k }] = (await db.query(
  "SELECT person_key AS k FROM trip WHERE external_id = 't1'")).rows;
check('the fixture really does generate a person key', !!k && k !== '', String(k));

for (const [label, key] of [
  ['a person on two accounts', k],
  ['an account standing in for a missing key', 'u-ghost'],
  ['an account whose row IS named', 'u-amina'],
  ['a key nobody holds', 'nobody-at-all'],
  ['the empty string, which must match nothing', ''],
  ['null', null],
]) {
  const [o, n] = [await setOf(OLD, key), await setOf(NEW, key)];
  check(`${label}: both forms agree`, o === n, `old=[${o}] new=[${n}]`);
}

console.log('\nand the answers are the right answers, not merely the same ones');

check('a folded key returns BOTH of that person’s accounts, once each',
  (await setOf(NEW, k)) === 'b-amina,u-amina', await setOf(NEW, k));
check('a nameless account is reached by its id, and deduped across its rows',
  (await setOf(NEW, 'u-ghost')) === 'u-ghost', await setOf(NEW, 'u-ghost'));
check('an id whose rows ARE named is not reachable by id — that is arm 1’s job',
  (await setOf(NEW, 'u-amina')) === '', await setOf(NEW, 'u-amina'));
check('the empty string matches nothing, so a blank key names nobody',
  (await setOf(NEW, '')) === '', await setOf(NEW, ''));

console.log('\nthe live SQL is the SQL that was tested');

/* An equivalence proved against a copy is an equivalence that stops being
   true the moment the copy drifts. */
const { readFileSync } = await import('node:fs');
const live = readFileSync('api/unauthorized_sql.js', 'utf8');
const shipped = live.slice(live.indexOf('AND e.driver_ext_id IN ('));
check('api/unauthorized_sql.js ships the two-arm UNION, not the OR',
  /UNION\s*\n\s*SELECT t3\.driver_ext_id FROM trip t3/.test(shipped)
  && !/OR \(coalesce\(btrim\(t3\.person_key\)/.test(shipped));
check('…including the <> \'\' that lets the PARTIAL index apply',
  /t3\.person_key IS NOT NULL AND t3\.person_key <> ''/.test(shipped));

console.log(`\n${pass} passed, ${fail} failed`);
await db.close();
process.exit(fail ? 1 : 0);
